### ISSUE TITLE
Put in row

### ISSUE THREAD

**Issue by victorRicardo1** [joshxfi/github-stats-generator#4]
Hi, how can i put the stats in row? I dont wanna collumn

**Comment by joshxfi** [comment]
> Hi, how can i put the stats in row? I dont wanna column

you can put the link in an `<img src="URL here" />` tag and put both of them inside of a `div` with `align=center`:
```html
<div align="center">
   // images here
</div>
```

which looks something like this:
```html
<div align="center">
  <img width="400" src="https://github-readme-stats.vercel.app/api?username=victorRicardo1&theme=calm&show_icons=true&hide_border=true&count_private=true" />
  <img width="400"  src="https://github-readme-streak-stats.herokuapp.com?user=victorRicardo1&theme=calm&hide_border=true" />
</div>
```

if you paste it in your `README.md`, it will result in:
<div align="center">
  <img width="400" src="https://github-readme-stats.vercel.app/api?username=victorRicardo1&theme=calm&show_icons=true&hide_border=true&count_private=true" />
  <img width="400"  src="https://github-readme-streak-stats.herokuapp.com?user=victorRicardo1&theme=calm&hide_border=true" />
</div>
